version: '3.9'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - ${API_PORT}:8000
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    tty: true
    restart: always
    user: root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    env_file:
      - ./backend/.env
    ports:
      - ${PGWEB_PORT}:8081
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
